
CONTROLLER_HOST = "host.docker.internal"
CONTROLLER_PORT = 50050
# CONTROLLER_TARGET = f"{CONTROLLER_HOST}:{CONTROLLER_PORT}"
CONTROLLER_TARGET = "172.17.0.1:50050"

NODE_PORT = 50051
DOCKER_IMAGE = "project2-image:latest"
DOCKER_NETWORK = "project2_net"
